-- Seed data for realistic Indian personal loan products (Banks and NBFCs)
-- Idempotent: safe to run multiple times using ON CONFLICT (provider, product_name) DO NOTHING

INSERT INTO loan_products (
    provider,
    product_name,
    interest_rate_min,
    interest_rate_max,
    min_income,
    min_credit_score,
    max_credit_score,
    min_age,
    max_age,
    employment_required,
    eligibility_notes,
    source_url,
    is_active
) VALUES
(
    'HDFC Bank',
    'Personal Loan for Salaried Professionals',
    10.50,
    21.00,
    25000.00,
    720,
    900,
    21,
    60,
    ARRAY['salaried'],
    'Preference to salaried employees of listed corporate firms or Tier-1 MNCs with minimum 2 years overall work experience.',
    'https://www.hdfcbank.com/personal/borrow/popular-loans/personal-loan',
    TRUE
),
(
    'State Bank of India',
    'Xpress Credit Personal Loan',
    11.15,
    14.30,
    15000.00,
    650,
    900,
    21,
    58,
    ARRAY['salaried'],
    'Must maintain salary account with SBI or public sector undertaking with at least 1 year in current organization.',
    'https://sbi.co.in/web/personal-banking/loans/personal-loans/xpress-credit',
    TRUE
),
(
    'ICICI Bank',
    'Personal Loan for Self-Employed',
    10.85,
    16.00,
    35000.00,
    700,
    900,
    25,
    65,
    ARRAY['self_employed'],
    'Minimum 3 years in current business; audited financial returns required for loan tenure above 36 months.',
    'https://www.icicibank.com/personal-banking/loans/personal-loan',
    TRUE
),
(
    'Bajaj Finserv',
    'Flexi Personal Loan',
    11.00,
    24.00,
    22000.00,
    685,
    900,
    21,
    67,
    ARRAY['salaried', 'self_employed'],
    'Requires active residential stability proof of at least 1 year.',
    'https://www.bajajfinserv.in/personal-loan',
    TRUE
),
(
    'Axis Bank',
    '24x7 Quick Personal Loan',
    10.75,
    22.00,
    30000.00,
    700,
    900,
    21,
    60,
    ARRAY['salaried', 'self_employed'],
    'Existing banking relationship preferred; no previous defaults on credit facilities in the last 12 months.',
    'https://www.axisbank.com/retail/loans/personal-loan',
    TRUE
),
(
    'Kotak Mahindra Bank',
    'Corporate Employee Personal Loan',
    10.99,
    24.00,
    20000.00,
    720,
    900,
    21,
    58,
    ARRAY['salaried'],
    'Open to permanent employees of selected corporate list with clean CIBIL repayment history.',
    'https://www.kotak.com/en/personal-banking/loans/personal-loan.html',
    TRUE
),
(
    'Tata Capital',
    'Multi-Purpose Personal Loan',
    10.99,
    19.99,
    20000.00,
    675,
    900,
    22,
    58,
    ARRAY['salaried', 'self_employed'],
    'Borderline credit profiles accepted if debt-to-income ratio is under 40% and applicant has no bounce records.',
    'https://www.tatacapital.com/personal-loan.html',
    TRUE
),
(
    'IDFC FIRST Bank',
    'First Personal Loan',
    10.49,
    25.00,
    25000.00,
    710,
    900,
    23,
    60,
    ARRAY['salaried', 'self_employed'],
    'Available across major metro and tier-2 locations with paperless e-KYC.',
    'https://www.idfcfirstbank.com/personal-banking/loans/personal-loan',
    TRUE
),
(
    'Poonawalla Fincorp',
    'Customized Personal Loan',
    9.99,
    20.00,
    30000.00,
    730,
    900,
    22,
    57,
    ARRAY['salaried'],
    'Minimum 1 year job stability with net take-home salary validated via bank statement upload.',
    'https://poonawallafincorp.com/personal-loan',
    TRUE
),
(
    'Navi Finserv',
    'Instant Digital Cash Loan',
    12.00,
    28.00,
    15000.00,
    600,
    900,
    18,
    65,
    ARRAY['salaried', 'self_employed'],
    'App-based fast disbursal; considers non-traditional credit signals for lower credit score brackets.',
    'https://navi.com/cash-loan',
    TRUE
)
ON CONFLICT (provider, product_name) DO NOTHING;
